### ISSUE TITLE
组织形式

### ISSUE THREAD

**Issue by DukeEnglish** [Dikea/awesome-interviews-cn#6]
我有个想法。
如果我现在想看一个机会。我第一时间 肯定是想要先看看自己最想去的公司有没有我想要的机会（实习、校招或者社招）。
但是我现在需要在目标公司中 寻找一下 到底是哪个才是我想要的？
不知道是不是只有我有这个感觉？

**Comment by Dikea** [comment]
那是不是按照岗位来布局会更好一些呢？比如前段、后端、算法之类的。

**Comment by DukeEnglish** [comment]
我觉得可以发自我的iPhone------------------ 原始邮件 ------------------发件人: Dikea  <notifications@github.com>发送时间: 2020年3月24日 17:35收件人: Dikea/awesome-interviews-cn <awesome-interviews-cn@noreply.github.com>抄送: Junyi_Li <ljyduke@gmail.com>, Author <author@noreply.github.com>主题: 回复：[Dikea/awesome-interviews-cn] 组织形式 (#6)
那是不是按照岗位来布局会更好一些呢？比如前段、后端、算法之类的。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Dikea/awesome-interviews-cn/issues/6#issuecomment-603131024",
"url": "https://github.com/Dikea/awesome-interviews-cn/issues/6#issuecomment-603131024",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
